import { writeFileSync } from "fs";
import { ScanResult, Endpoint } from "../engine/types.js";
import { Output } from "./Output.js";

export class CurlOutput implements Output {
  format(result: ScanResult): string {
    const lines: string[] = [
      `# ${result.projectName} API — cURL Commands`,
      `# Generated by API Scanner v1.0.0`,
      `# ${result.scannedAt}`,
      `# Endpoints: ${result.totalEndpoints}`,
      "",
    ];

    for (const svc of result.services) {
      for (const ep of svc.endpoints) {
        if (ep.method === "CLI" || ep.method === "TCP" || ep.method === "CONFIG") continue;
        const curl = this.toCurl(ep, svc);
        lines.push(curl);
        lines.push("");
      }
    }

    return lines.join("\n");
  }

  private toCurl(ep: Endpoint, svc: any): string {
    const url = `http://localhost:${svc.port || 8080}${ep.path}`;
    const parts = [`curl -X ${ep.method} "${url}"`];

    parts.push(`  -H "Content-Type: application/json"`);

    if (ep.headers) {
      for (const h of ep.headers) {
        parts.push(`  -H "${h}"`);
      }
    }

    if (ep.tags.includes("authenticated")) {
      parts.push(`  -H "Authorization: Bearer <token>"`);
    }

    if (ep.method === "POST" || ep.method === "PUT" || ep.method === "PATCH") {
      parts.push(`  -d '{}'`);
    }

    return `# ${ep.source.file}:${ep.source.line}\n${parts.join(" \\\n")}`;
  }

  write(result: ScanResult, path: string): void {
    writeFileSync(path, this.format(result), "utf-8");
  }
}
