import { writeFileSync } from "fs";
import { ScanResult, Endpoint } from "../engine/types.js";

export class OpenAPIOutput {
  format(result: ScanResult): string {
    const paths: Record<string, any> = {};

    for (const service of result.services) {
      for (const ep of service.endpoints) {
        if (ep.method === "CLI" || ep.method === "TCP" || ep.method === "CONFIG") continue;

        const cleanPath = ep.path
          .replace(/\{(\w+)\}/g, (_, name) => `{${name}}`)
          .replace(/:\w+/g, (m) => `{${m.slice(1)}}`);

        if (!paths[cleanPath]) paths[cleanPath] = {};

        const method = ep.method.toLowerCase();
        if (!paths[cleanPath][method]) {
          paths[cleanPath][method] = {
            summary: `Endpoint in ${ep.service}`,
            tags: [ep.service, ...ep.tags.filter((t) => !["health", "prover", "verifier", "build"].includes(t))],
            parameters: ep.parameters?.map((p) => ({
              name: p.name,
              in: p.type,
              required: p.required ?? false,
              schema: { type: "string" },
            })) || [],
            responses: {
              "200": { description: "OK" },
              "400": { description: "Bad Request" },
              "500": { description: "Internal Server Error" },
            },
            "x-zero-proof": {
              service: ep.service,
              source: `${ep.source.file}:${ep.source.line}`,
              tags: ep.tags,
            },
          };
        }
      }
    }

    const spec = {
      openapi: "3.1.0",
      info: {
        title: `${result.projectName} API`,
        version: result.projectVersion,
        description: `Auto-discovered API surface for ${result.projectName}. Generated by ScanDog.`,
      },
      servers: [
        { url: "http://localhost:8080", description: "Gateway / Monolithic Server" },
        { url: "http://localhost:8081", description: "Build Service" },
        { url: "http://localhost:8082", description: "Prover Service" },
      ],
      paths,
      "x-total-endpoints": result.totalEndpoints,
    };

    return JSON.stringify(spec, null, 2);
  }

  write(result: ScanResult, path: string): void {
    writeFileSync(path, this.format(result), "utf-8");
  }
}
