import { writeFileSync } from "fs";
import { ScanResult, Endpoint } from "../engine/types.js";
import { Output } from "./Output.js";

export class OpenAPIOutput implements Output {
  format(result: ScanResult): string {
    const paths: Record<string, any> = {};
    const allServers = new Set<string>();

    for (const service of result.services) {
      for (const ep of service.endpoints) {
        if (ep.method === "CLI" || ep.method === "TCP" || ep.method === "CONFIG") continue;

        const cleanPath = ep.path
          .replace(/\{(\w+)\}/g, (_, name) => `{${name}}`)
          .replace(/:\w+/g, (m) => `{${m.slice(1)}}`);

        if (!paths[cleanPath]) paths[cleanPath] = {};

        const method = ep.method.toLowerCase();
        if (!paths[cleanPath][method]) {
          const serverUrl = service.port ? `http://localhost:${service.port}` : "http://localhost:8080";
          allServers.add(serverUrl);

          paths[cleanPath][method] = {
            summary: ep.tags.includes("health") ? "Health check endpoint" : `Endpoint in ${ep.service}`,
            tags: [ep.service, ...ep.tags.filter((t) => !["health", "prover", "verifier", "build"].includes(t))],
            parameters: [
              ...(ep.parameters?.filter((p) => p.type === "path" || p.type === "query").map((p) => ({
                name: p.name,
                in: p.type === "path" ? "path" : "query",
                required: p.required ?? false,
                schema: { type: "string" },
              })) || []),
            ],
            responses: {
              "200": { description: ep.tags.includes("health") ? "Service is healthy" : "OK" },
              "400": { description: "Bad Request" },
              "500": { description: "Internal Server Error" },
            },
            "x-api-scanner": {
              service: ep.service,
              source: `${ep.source.file}:${ep.source.line}`,
              tags: ep.tags,
              technology: ep.technology || "",
            },
          };
        }
      }
    }

    const spec = {
      openapi: "3.1.0",
      info: {
        title: `${result.projectName} API`,
        version: result.projectVersion,
        description: `Auto-discovered API surface for ${result.projectName}. Generated by API Scanner.`,
      },
      servers: [...allServers].map((url) => ({ url })),
      paths,
      "x-total-endpoints": result.totalEndpoints,
      "x-technologies": result.technologies || [],
    };

    return JSON.stringify(spec, null, 2);
  }

  write(result: ScanResult, path: string): void {
    writeFileSync(path, this.format(result), "utf-8");
  }
}
