import { writeFileSync } from "fs";
import { ScanResult, Endpoint } from "../engine/types.js";
import { Output } from "./Output.js";

export class PowerShellOutput implements Output {
  format(result: ScanResult): string {
    const lines: string[] = [
      `# ${result.projectName} API — PowerShell Invoke-WebRequest Commands`,
      `# Generated by ScanDog v1.0.0`,
      `# ${result.scannedAt}`,
      `# Endpoints: ${result.totalEndpoints}`,
      "",
      `# Variables`,
      `$baseUrl = "http://localhost:8080"`,
      `$headers = @{ "Content-Type" = "application/json" }`,
      "",
    ];

    for (const svc of result.services) {
      for (const ep of svc.endpoints) {
        if (ep.method === "CLI" || ep.method === "TCP" || ep.method === "CONFIG") continue;
        lines.push(this.toPowerShell(ep, svc));
        lines.push("");
      }
    }

    return lines.join("\n");
  }

  private toPowerShell(ep: Endpoint, svc: any): string {
    const url = `http://localhost:${svc.port || 8080}${ep.path}`;
    const varName = ep.path.replace(/[^a-zA-Z0-9]/g, "_").replace(/^_/, "").toLowerCase() || "endpoint";

    const parts: string[] = [
      `# ${ep.method} ${ep.path} (${ep.source.file}:${ep.source.line})`,
      `# Tags: ${ep.tags.join(", ")}`,
      `$${varName} = Invoke-WebRequest \\`,
      `  -Uri "${url}" \\`,
      `  -Method ${ep.method} \\`,
      `  -Headers $headers`,
    ];

    if (ep.tags.includes("authenticated")) {
      parts.splice(parts.length - 1, 0, `  -Headers @{ "Authorization" = "Bearer <token>" } \\`);
    }

    if (ep.method === "POST" || ep.method === "PUT" || ep.method === "PATCH") {
      parts.push(`  -Body (ConvertTo-Json @{})`);
    }

    return parts.join(" \\\n");
  }

  write(result: ScanResult, path: string): void {
    writeFileSync(path, this.format(result), "utf-8");
  }
}
