import { writeFileSync } from "fs";
import { ScanResult } from "../engine/types.js";
import { Output } from "./Output.js";

export class TomlOutput implements Output {
  format(result: ScanResult): string {
    const lines: string[] = [
      `# ${result.projectName} Attack Surface`,
      `# Generated by API Scanner v1.0.0`,
      `# ${result.scannedAt}`,
      "",
      "[project]",
      `name = "${result.projectName}"`,
      `version = "${result.projectVersion}"`,
      `total_endpoints = ${result.totalEndpoints}`,
      `scanned_at = "${result.scannedAt}"`,
      "",
    ];

    if (result.technologies && result.technologies.length > 0) {
      lines.push("[technologies]");
      for (const tech of result.technologies) {
        lines.push(`"${tech}" = true`);
      }
      lines.push("");
    }

    lines.push("[tags]");
    lines.push(`shadow = ${result.tags.shadow}`);
    lines.push(`deprecated = ${result.tags.deprecated || 0}`);
    lines.push(`authenticated = ${result.tags.authenticated || 0}`);
    lines.push(`prover = ${result.tags.prover || 0}`);
    lines.push(`verifier = ${result.tags.verifier || 0}`);
    lines.push(`health = ${result.tags.health || 0}`);
    lines.push("");

    for (const svc of result.services) {
      const section = `services.${svc.name.replace(/[^a-zA-Z0-9]/g, "_")}`;
      lines.push(`[${section}]`);
      lines.push(`name = "${svc.name}"`);
      lines.push(`type = "${svc.type}"`);
      if (svc.port) lines.push(`port = ${svc.port}`);
      lines.push("");

      for (let i = 0; i < svc.endpoints.length; i++) {
        const ep = svc.endpoints[i];
        const epSection = `${section}.endpoints.${i}`;
        lines.push(`[${epSection}]`);
        lines.push(`method = "${ep.method}"`);
        lines.push(`path = "${ep.path}"`);
        lines.push(`file = "${ep.source.file}"`);
        lines.push(`line = ${ep.source.line}`);
        if (ep.tags.length > 0) {
          lines.push(`tags = [${ep.tags.map((t) => `"${t}"`).join(", ")}]`);
        }
        lines.push("");
      }
    }

    return lines.join("\n");
  }

  write(result: ScanResult, path: string): void {
    writeFileSync(path, this.format(result), "utf-8");
  }
}
