blank_issues_enabled: false
contact_links:
  - name: TSC Wireshift Documentation
    url: https://github.com/al-sultani/TSC Wireshift/blob/main/docs/
    about: Check our documentation before opening an issue 