import React, { useState, useEffect, useMemo } from "react";
import Link from "@docusaurus/Link";
import styles from "./styles.module.css";

const SERVICE_ICONS = {
  server: "\uD83D\uDEE1\uFE0F",
  gateway: "\uD83D\uDEAA",
  "build-service": "\uD83D\uDD27",
  "prover-service": "\u2699\uFE0F",
  cli: "\uD83D\uDCBB",
};

const METHOD_CLASSES = {
  GET: styles.methodGet, POST: styles.methodPost,
  PUT: styles.methodPut, DELETE: styles.methodDelete,
  ANY: styles.methodAny, CLI: styles.methodCli,
  TCP: styles.methodTcp, CONFIG: styles.methodConfig,
};

const TAG_CLASSES = {
  health: styles.tagHealth, prover: styles.tagProver,
  verifier: styles.tagVerifier, shadow: styles.tagShadow,
  config: styles.tagConfig, docker: styles.tagDocker,
  cli: styles.tagCli, command: styles.tagCommand,
  build: styles.tagBuild, upstream: styles.tagUpstream,
};

function buildMermaid(data) {
  const lines = ["graph TB"];
  lines.push("  title[ScanDog Attack Surface Architecture]");
  lines.push("  style title fill:#8d4c4c,color:#fff,font-size:16px");
  lines.push("");

  for (const svc of data.services) {
    const id = svc.name.replace(/[^a-zA-Z0-9]/g, "_");
    const label = `${svc.name}\\n${svc.type}${svc.port ? ` :${svc.port}` : ""}`;
    lines.push(`  ${id}["${label}"]`);
    for (const ep of svc.endpoints) {
      if (ep.method === "CLI" || ep.method === "TCP" || ep.method === "CONFIG") continue;
      const eid = `${id}_${ep.method}_${ep.path.replace(/[^a-zA-Z0-9]/g, "_")}`;
      lines.push(`  ${eid}["${ep.method} ${ep.path}"]`);
      lines.push(`  ${id} --> ${eid}`);
    }
  }

  lines.push("");
  for (let i = 0; i < data.services.length - 1; i++) {
    const a = data.services[i].name.replace(/[^a-zA-Z0-9]/g, "_");
    const b = data.services[i + 1].name.replace(/[^a-zA-Z0-9]/g, "_");
    lines.push(`  ${a} -.-> ${b}`);
  }

  return lines.join("\n");
}



const EMPTY_DATA = {
  projectName: "ScanDog",
  projectVersion: "1.0.0",
  scannedAt: new Date().toISOString(),
  services: [],
  clis: [],
  totalEndpoints: 0,
  tags: { shadow: 0, prover: 0, verifier: 0, health: 0, deprecated: 0, authenticated: 0, websocket: 0, static: 0, callee: 0, aiContext: 0, graphql: 0, jwt: 0, fileUpload: 0 },
  technologies: [],
  warnings: [],
};

export default function ScanDog() {
  const [data, setData] = useState(EMPTY_DATA);
  const [search, setSearch] = useState("");
  const [methodFilter, setMethodFilter] = useState("all");
  const [activeTab, setActiveTab] = useState("endpoints");
  const [rawTab, setRawTab] = useState("json");
  const [expandedServices, setExpandedServices] = useState(new Set());
  const [copied, setCopied] = useState(false);
  const [mermaidSvg, setMermaidSvg] = useState("");
  const [scanUrl, setScanUrl] = useState("");
  const [urlScanning, setUrlScanning] = useState(false);
  const [urlError, setUrlError] = useState("");

  useEffect(() => {
    if (!data || activeTab !== "architecture") return;
    const def = buildMermaid(data);

    const renderMermaid = async () => {
      try {
        const mermaid = await import("mermaid");
        mermaid.default.initialize({
          theme: document.documentElement.getAttribute("data-theme") === "dark" ? "dark" : "default",
        });
        const { svg } = await mermaid.default.render("scandog-mermaid-svg", def);
        setMermaidSvg(svg);
      } catch {}
    };

    const timer = setTimeout(renderMermaid, 200);
    return () => clearTimeout(timer);
  }, [data, activeTab]);

  const toggleService = (name) => {
    setExpandedServices((p) => {
      const n = new Set(p);
      if (n.has(name)) n.delete(name); else n.add(name);
      return n;
    });
  };

  const allEndpoints = useMemo(() => {
    if (!data) return [];
    const eps = [];
    for (const svc of data.services) {
      for (const ep of svc.endpoints) {
        eps.push({ ...ep, _service: svc.name, _type: svc.type });
      }
    }
    return eps;
  }, [data]);

  const filteredEndpoints = useMemo(() => {
    return allEndpoints.filter((ep) => {
      if (methodFilter !== "all" && ep.method !== methodFilter) return false;
      if (!search) return true;
      const q = search.toLowerCase();
      return (
        ep.path.toLowerCase().includes(q) ||
        ep.method.toLowerCase().includes(q) ||
        ep._service.toLowerCase().includes(q) ||
        ep.tags.some((t) => t.toLowerCase().includes(q)) ||
        ep.source.file.toLowerCase().includes(q)
      );
    });
  }, [allEndpoints, search, methodFilter]);

  const getRawContent = (fmt) => {
    if (!data) return "";
    if (fmt === "json") return JSON.stringify(data, null, 2);

    const lines = [`# ScanDog Attack Surface — ${fmt.toUpperCase()}`, `# Generated by ScanDog v1.0.0`, `# ${data.scannedAt}`, ""];

    if (fmt === "yaml") {
      lines.push("project:");
      lines.push(`  name: ${data.projectName}`);
      lines.push(`  version: ${data.projectVersion}`);
      lines.push(`  scanned: ${data.scannedAt}`);
      lines.push(`  total_endpoints: ${data.totalEndpoints}`);
      lines.push("");
      lines.push("services:");
      for (const svc of data.services) {
        lines.push(`  ${svc.name}:`);
        lines.push(`    type: ${svc.type}`);
        if (svc.port) lines.push(`    port: ${svc.port}`);
        lines.push("    endpoints:");
        for (const ep of svc.endpoints) {
          lines.push(`      - method: ${ep.method}`);
          lines.push(`        path: ${ep.path}`);
          lines.push(`        tags: [${ep.tags.join(", ")}]`);
          lines.push(`        source: ${ep.source.file}:${ep.source.line}`);
        }
      }
    }

    if (fmt === "openapi") {
      const paths = {};
      for (const svc of data.services) {
        for (const ep of svc.endpoints) {
          if (ep.method === "CLI" || ep.method === "TCP" || ep.method === "CONFIG") continue;
          const path = ep.path;
          if (!paths[path]) paths[path] = {};
          const m = ep.method.toLowerCase();
          paths[path][m] = {
            summary: `${ep.method} ${ep.path}`,
            tags: [svc.name, ...ep.tags],
            responses: { "200": { description: "OK" } },
            "x-scandog": { service: svc.name, source: `${ep.source.file}:${ep.source.line}` },
          };
        }
      }
      const spec = {
        openapi: "3.1.0",
        info: { title: `${data.projectName} API`, version: data.projectVersion, description: "Auto-discovered by ScanDog" },
        servers: [
          { url: "http://localhost:8080", description: "Gateway" },
          { url: "http://localhost:8081", description: "Build Service" },
          { url: "http://localhost:8082", description: "Prover Service" },
        ],
        paths,
      };
      lines.push(JSON.stringify(spec, null, 2));
    }

    if (fmt === "sarif") {
      const results = [];
      data.services.forEach((svc) => {
        svc.endpoints.forEach((ep, i) => {
          results.push({
            ruleId: `ZP-${String(i + 1).padStart(4, "0")}`,
            level: "note",
            message: { text: `${ep.method} ${ep.path} in ${svc.name}` },
            locations: [{ physicalLocation: { artifactLocation: { uri: ep.source.file }, region: { startLine: ep.source.line } } }],
            properties: { tags: ep.tags, service: svc.name },
          });
        });
      });
      const sarif = {
        $schema: "https://docs.oasis-open.org/sarif/sarif/v2.1.0/errata01/os/schemas/sarif-2.1.0-errata01-os-schema.json",
        version: "2.1.0",
        runs: [{ tool: { driver: { name: "ScanDog", version: "1.0.0" } }, results }],
      };
      lines.push(JSON.stringify(sarif, null, 2));
    }

    return lines.join("\n");
  };

  const download = (format) => {
    const content = format === "json"
      ? JSON.stringify(data, null, 2)
      : getRawContent(format);
    const mimeTypes = {
      json: "application/json", yaml: "text/yaml",
      openapi: "application/json", sarif: "application/json",
      html: "text/html", mermaid: "text/plain",
    };
    const blob = new Blob([content], { type: mimeTypes[format] || "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `scandog-attack-surface.${format === "openapi" ? "json" : format}`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const copyRaw = () => {
    navigator.clipboard.writeText(getRawContent(rawTab));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleUrlScan = async () => {
    const trimmed = scanUrl.trim();
    if (!trimmed) { setUrlError("Please enter a GitHub URL"); return; }
    if (!trimmed.includes("github.com")) { setUrlError("Only GitHub URLs are supported"); return; }
    setUrlScanning(true);
    setUrlError("");
    try {
      const res = await fetch("/api/scan-url", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ url: trimmed }),
      });
      if (!res.ok) {
        const err = await res.json().catch(() => ({}));
        throw new Error(err.error || `Server error: ${res.status}`);
      }
      const result = await res.json();
      setData(result);
      setExpandedServices(new Set(result.services.map((s) => s.name)));
      setActiveTab("endpoints");
    } catch (e) {
      setUrlError(e.message);
    } finally {
      setUrlScanning(false);
    }
  };

  const cta = (
    <>
      <Link className={styles.ctaBtn} to="/scandog-setup">
        Get Started
      </Link>
      <Link className={styles.ctaBtn} to="/tscscan" style={{ marginLeft: "0.5rem" }}>
        tscscan
      </Link>
    </>
  );

  return (
    <div className={styles.container}>
      <div className={styles.ctaBar}>{cta}</div>

      {/* Hero */}
      <div className={styles.hero}>
        <div className={styles.heroBadge}>
          {data.totalEndpoints > 0 ? `ScanDog v1.0.0` : `ScanDog — Ready`}
        </div>
        <h1 className={styles.heroTitle}>
          {data.totalEndpoints > 0 ? data.projectName : `ScanDog Attack Surface Scanner`}
        </h1>
        <p className={styles.heroSub}>
          {data.totalEndpoints > 0
            ? `Attack Surface Report &mdash; ${data.totalEndpoints} endpoints &middot; ${data.services.length} services &middot; ${data.clis.length} CLI tools &middot; ${new Date(data.scannedAt).toLocaleDateString()}`
            : `Paste a GitHub URL below to scan any repository &mdash; no installation needed`
          }
        </p>
      </div>

      {/* URL Scan Bar */}
      <div className={styles.urlScanSection}>
        <div className={styles.urlScanHeader}>
          <h2 className={styles.urlScanTitle}>\uD83C\uDF10 Scan Any GitHub Repo</h2>
          <p className={styles.urlScanSub}>Paste a GitHub URL &mdash; no installation needed</p>
        </div>
        <div className={styles.urlScanForm}>
          <input
            className={styles.urlScanInput}
            type="text"
            placeholder="https://github.com/user/repo"
            value={scanUrl}
            onChange={(e) => { setScanUrl(e.target.value); setUrlError(""); }}
            onKeyDown={(e) => { if (e.key === "Enter") handleUrlScan(); }}
          />
          <button className={styles.urlScanBtn} onClick={handleUrlScan} disabled={urlScanning}>
            {urlScanning ? "Scanning..." : "Scan"}
          </button>
        </div>
        {urlError && <div className={styles.urlScanError}>{urlError}</div>}
      </div>

      {/* Scan Routing Engine */}
      <div className={styles.routeSection}>
        <div className={styles.routeHeader}>
          <h2 className={styles.routeTitle}>\u26A1 Scan Routing Engine</h2>
          <p className={styles.routeSub}>Route scan results by rule &mdash; inspired by OpenRouter's provider routing &mdash; <code>--route "tag=shadow->deliver:zap"</code></p>
        </div>

        <div className={styles.routeBlock}>
          <div className={styles.routeCmd}>
            <span className={styles.routeLabel}>Exclude</span>
            <code>--route "tag=health->exclude"</code>
            <span className={styles.routeDesc}>Remove health-check endpoints from results</span>
          </div>
          <div className={styles.routeCmd}>
            <span className={styles.routeLabel}>Deliver</span>
            <code>--route "method=POST->deliver:burp"</code>
            <span className={styles.routeDesc}>Route POST endpoints to Burp Suite</span>
          </div>
          <div className={styles.routeCmd}>
            <span className={styles.routeLabel}>Split</span>
            <code>--route "path=/api/**->split:file=api-spec.json"</code>
            <span className={styles.routeDesc}>Save matched endpoints to separate file</span>
          </div>
          <div className={styles.routeCmd}>
            <span className={styles.routeLabel}>Tag</span>
            <code>--route "tag=shadow->tag:critical"</code>
            <span className={styles.routeDesc}>Add extra tags to matched endpoints</span>
          </div>
          <div className={styles.routeCmd}>
            <span className={styles.routeLabel}>Reroute</span>
            <code>--route "path=/old/**->reroute:path=/api/v2/**"</code>
            <span className={styles.routeDesc}>Rewrite endpoint paths/methods</span>
          </div>
          <div className={styles.routeCmd}>
            <span className={styles.routeLabel}>Chain</span>
            <code>--route "tag=shadow->deliver:zap" --route "tag=shadow->split:file=shadow.json"</code>
            <span className={styles.routeDesc}>Multiple rules run in order</span>
          </div>
        </div>

        <div className={styles.routeActions}>
          <Link className={styles.routeDocBtn} to="/scandog-setup#routing">Routing Docs \u2192</Link>
        </div>
      </div>

      {/* TSC Tools */}
      <div className={styles.routeSection} style={{ marginTop: "1.5rem" }}>
        <div className={styles.routeHeader}>
          <h2 className={styles.routeTitle}>TSC Tool Arsenal</h2>
          <p className={styles.routeSub}>Full-fledged offensive tools — each is a standalone CLI <code>npm install -g</code> away</p>
        </div>
        <div className={styles.routeBlock}>
          <div className={styles.routeCmd}>
            <span className={styles.routeLabel} style={{background:"#8b5cf6"}}>tsc-mesh</span>
            <code>Multi-Protocol C2 Mesh</code>
            <span className={styles.routeDesc}>HTTP + DNS + WebSocket C2 with automatic failover</span>
            <Link className={styles.routeDocBtn} to="/tsc-mesh" style={{marginLeft:"auto",fontSize:"0.7rem",padding:"0.2rem 0.6rem"}}>Open &rarr;</Link>
          </div>
          <div className={styles.routeCmd}>
            <span className={styles.routeLabel} style={{background:"#0891b2"}}>tsc-lotl</span>
            <code>Living-off-the-Land C2</code>
            <span className={styles.routeDesc}>C2 via Google Drive, GitHub Gists, Notion, Slack, Discord</span>
            <Link className={styles.routeDocBtn} to="/tsc-lotl" style={{marginLeft:"auto",fontSize:"0.7rem",padding:"0.2rem 0.6rem"}}>Open &rarr;</Link>
          </div>
          <div className={styles.routeCmd}>
            <span className={styles.routeLabel} style={{background:"#d97706"}}>tsc-polymorph</span>
            <code>Polymorphic Payload Generator</code>
            <span className={styles.routeDesc}>Unique-signature payloads per generation — AES + XOR + dead code</span>
            <Link className={styles.routeDocBtn} to="/tsc-polymorph" style={{marginLeft:"auto",fontSize:"0.7rem",padding:"0.2rem 0.6rem"}}>Open &rarr;</Link>
          </div>
          <div className={styles.routeCmd}>
            <span className={styles.routeLabel} style={{background:"#16a34a"}}>tsc-p2p</span>
            <code>P2P Botnet Mesh</code>
            <span className={styles.routeDesc}>Kademlia DHT + gossip protocol — no central C2 needed</span>
            <Link className={styles.routeDocBtn} to="/tsc-p2p" style={{marginLeft:"auto",fontSize:"0.7rem",padding:"0.2rem 0.6rem"}}>Open &rarr;</Link>
          </div>
          <div className={styles.routeCmd}>
            <span className={styles.routeLabel} style={{background:"#dc2626"}}>tsc-ai</span>
            <code>AI Evasion Engine</code>
            <span className={styles.routeDesc}>Sandbox detection + AV fingerprinting + adaptive beacon q-learning</span>
            <Link className={styles.routeDocBtn} to="/tsc-ai" style={{marginLeft:"auto",fontSize:"0.7rem",padding:"0.2rem 0.6rem"}}>Open &rarr;</Link>
          </div>
        </div>
      </div>

      {/* Stats */}
      <div className={styles.statsGrid}>
        <div className={styles.statCard}>
          <div className={styles.statValue}>{data.totalEndpoints}</div>
          <div className={styles.statLabel}>Total Endpoints</div>
        </div>
        <div className={styles.statCard}>
          <div className={`${styles.statValue} ${styles.statInfo}`}>{data.services.length}</div>
          <div className={styles.statLabel}>Services</div>
        </div>
        <div className={styles.statCard}>
          <div className={`${styles.statValue} ${styles.statInfo}`}>{data.clis.length}</div>
          <div className={styles.statLabel}>CLI Tools</div>
        </div>
        <div className={styles.statCard}>
          <div className={`${styles.statValue} ${data.tags.shadow > 0 ? styles.statDanger : ""}`}>
            {data.tags.shadow}
          </div>
          <div className={styles.statLabel}>Shadow APIs</div>
        </div>
        <div className={styles.statCard}>
          <div className={`${styles.statValue} ${styles.statSuccess}`}>{data.tags.prover}</div>
          <div className={styles.statLabel}>Prover</div>
        </div>
        <div className={styles.statCard}>
          <div className={`${styles.statValue} ${styles.statSuccess}`}>{data.tags.verifier}</div>
          <div className={styles.statLabel}>Verifier</div>
        </div>
      </div>

      {/* Alerts */}
      {data.tags.shadow > 0 && (
        <div className={styles.alertBar}>
          <div className={`${styles.alert} ${styles.alertDanger}`}>
            <strong>{data.tags.shadow} shadow API{data.tags.shadow !== 1 ? "s" : ""} detected</strong>
            &mdash; These endpoints may expose internal functionality. Review access controls.
          </div>
        </div>
      )}

      {/* Tabs */}
      <div className={styles.tabs}>
        <button className={`${styles.tab} ${activeTab === "endpoints" ? styles.tabActive : ""}`} onClick={() => setActiveTab("endpoints")}>
          Endpoints
        </button>
        <button className={`${styles.tab} ${activeTab === "architecture" ? styles.tabActive : ""}`} onClick={() => setActiveTab("architecture")}>
          Architecture
        </button>
        <button className={`${styles.tab} ${activeTab === "report" ? styles.tabActive : ""}`} onClick={() => setActiveTab("report")}>
          Full Report
        </button>
        <button className={`${styles.tab} ${activeTab === "raw" ? styles.tabActive : ""}`} onClick={() => setActiveTab("raw")}>
          Raw Data
        </button>
      </div>

      {/* Tab: Endpoints */}
      {activeTab === "endpoints" && (
        <>
          <div className={styles.filterBar}>
            <input className={styles.searchInput} type="text" placeholder="Search paths, methods, services, tags..." value={search} onChange={(e) => setSearch(e.target.value)} />
            <select className={styles.filterSelect} value={methodFilter} onChange={(e) => setMethodFilter(e.target.value)}>
              <option value="all">All Methods</option>
              <option value="GET">GET</option>
              <option value="POST">POST</option>
              <option value="ANY">ANY</option>
              <option value="CLI">CLI</option>
              <option value="TCP">TCP</option>
              <option value="CONFIG">CONFIG</option>
            </select>
            <span className={styles.filterCount}>{filteredEndpoints.length} of {allEndpoints.length}</span>
          </div>

          {data.services.map((svc) => {
            const svcEp = svc.endpoints;
            const isExpanded = expandedServices.has(svc.name);
            const hasMatch = svcEp.some((ep) => {
              if (methodFilter !== "all" && ep.method !== methodFilter) return false;
              if (!search) return true;
              const q = search.toLowerCase();
              return ep.path.toLowerCase().includes(q) || ep.method.toLowerCase().includes(q) || ep.tags.some((t) => t.toLowerCase().includes(q)) || ep.source.file.toLowerCase().includes(q);
            });
            if ((search || methodFilter !== "all") && !hasMatch) return null;

            const icon = SERVICE_ICONS[svc.type] || "\uD83D\uDCA1";

            return (
              <div className={styles.serviceCard} key={svc.name}>
                <div className={styles.serviceHeader} onClick={() => toggleService(svc.name)}>
                  <span className={styles.serviceIcon}>{icon}</span>
                  <span className={styles.serviceName}>{svc.name}</span>
                  <span className={styles.serviceBadge}>{svc.type}</span>
                  {svc.port ? <span className={styles.servicePort}>:{svc.port}</span> : null}
                  <span className={styles.serviceEpCount}>{svcEp.length}</span>
                  <span className={`${styles.chevron} ${isExpanded ? styles.chevronOpen : ""}`}>&#9654;</span>
                </div>
                {isExpanded && (
                  <table className={styles.endpointTable}>
                    <thead>
                      <tr><th>Method</th><th>Path</th><th>Tags</th><th>Source</th></tr>
                    </thead>
                    <tbody>
                      {svcEp.filter((ep) => {
                        if (methodFilter !== "all" && ep.method !== methodFilter) return false;
                        if (!search) return true;
                        const q = search.toLowerCase();
                        return ep.path.toLowerCase().includes(q) || ep.method.toLowerCase().includes(q) || ep.tags.some((t) => t.toLowerCase().includes(q)) || ep.source.file.toLowerCase().includes(q);
                      }).map((ep, i) => (
                        <tr key={i}>
                          <td><span className={`${styles.methodBadge} ${METHOD_CLASSES[ep.method] || styles.methodAny}`}>{ep.method}</span></td>
                          <td className={styles.pathCell}><code>{ep.path}</code></td>
                          <td>
                            <div className={styles.tagList}>
                              {ep.tags.map((t, j) => (
                                <span key={j} className={`${styles.tag} ${TAG_CLASSES[t] || ""}`}>{t}</span>
                              ))}
                            </div>
                          </td>
                          <td>
                            <a className={styles.sourceLink} href={`https://github.com/SURUJ404/Zero-proof/blob/main/${ep.source.file}`} target="_blank" rel="noopener">
                              {ep.source.file}:{ep.source.line}
                            </a>
                          </td>
                        </tr>
                      ))}
                      {svcEp.filter((ep) => {
                        if (methodFilter !== "all" && ep.method !== methodFilter) return false;
                        if (!search) return true;
                        const q = search.toLowerCase();
                        return ep.path.toLowerCase().includes(q) || ep.method.toLowerCase().includes(q) || ep.tags.some((t) => t.toLowerCase().includes(q)) || ep.source.file.toLowerCase().includes(q);
                      }).length === 0 && (
                        <tr className={styles.emptyRow}><td colSpan={4}>No matching endpoints</td></tr>
                      )}
                    </tbody>
                  </table>
                )}
              </div>
            );
          })}

          {/* CLI Tools */}
          <div className={styles.cliSection}>
            <div className={styles.cliHeader}>CLI Tools ({data.clis.length})</div>
            <div className={styles.cliBody}>
              {data.clis.map((cli, i) => (
                <div className={styles.cliItem} key={i}>
                  <div className={styles.cliName}>{cli.binary}</div>
                  <div className={styles.cliDesc}>{cli.description}</div>
                  <div>{cli.commands.map((cmd, j) => (
                    <code className={styles.cliCmd} key={j}>{cli.binary} {cmd.name}</code>
                  ))}</div>
                </div>
              ))}
            </div>
          </div>
        </>
      )}

      {/* Tab: Architecture */}
      {activeTab === "architecture" && (
        <div className={styles.diagramSection}>
          {mermaidSvg ? (
            <div dangerouslySetInnerHTML={{ __html: mermaidSvg }} />
          ) : (
            <div style={{ textAlign: "center", padding: "2rem", color: "var(--ifm-color-emphasis-500)" }}>
              Generating architecture diagram...
            </div>
          )}
          <div style={{ textAlign: "center", marginTop: "0.75rem" }}>
            <button className={styles.downloadBtn} onClick={() => download("mermaid")}>Download Mermaid Source</button>
          </div>
        </div>
      )}

      {/* Tab: Full Report */}
      {activeTab === "report" && (
        <div className={styles.fullReport}>
          <h2>Service Inventory</h2>
          <table className={styles.reportTable}>
            <thead><tr><th>Service</th><th>Type</th><th>Port</th><th>Endpoints</th><th>Methods</th></tr></thead>
            <tbody>
              {data.services.map((svc, i) => {
                const methods = [...new Set(svc.endpoints.map((e) => e.method))].join(", ");
                return (
                  <tr key={i} className={i % 2 === 1 ? styles.reportRowEven : ""}>
                    <td><strong>{svc.name}</strong></td>
                    <td><span className={styles.serviceBadge}>{svc.type}</span></td>
                    <td>{svc.port || "-"}</td>
                    <td>{svc.endpoints.length}</td>
                    <td style={{ fontSize: "0.7rem" }}>{methods}</td>
                  </tr>
                );
              })}
            </tbody>
          </table>

          <h2 style={{ marginTop: "1.5rem" }}>Endpoint Catalog</h2>
          <table className={styles.reportTable}>
            <thead><tr><th>#</th><th>Method</th><th>Path</th><th>Service</th><th>Tags</th><th>Source</th></tr></thead>
            <tbody>
              {allEndpoints.map((ep, i) => (
                <tr key={i} className={i % 2 === 1 ? styles.reportRowEven : ""}>
                  <td style={{ color: "var(--ifm-color-emphasis-500)", fontSize: "0.7rem" }}>{i + 1}</td>
                  <td><span className={`${styles.methodBadge} ${METHOD_CLASSES[ep.method] || styles.methodAny}`}>{ep.method}</span></td>
                  <td className={styles.pathCell}><code>{ep.path}</code></td>
                  <td style={{ fontSize: "0.75rem" }}>{ep._service}</td>
                  <td><div className={styles.tagList}>{ep.tags.map((t, j) => (<span key={j} className={`${styles.tag} ${TAG_CLASSES[t] || ""}`}>{t}</span>))}</div></td>
                  <td><a className={styles.sourceLink} href={`https://github.com/SURUJ404/Zero-proof/blob/main/${ep.source.file}`} target="_blank" rel="noopener">{ep.source.file}:{ep.source.line}</a></td>
                </tr>
              ))}
            </tbody>
          </table>

          <h2 style={{ marginTop: "1.5rem" }}>Security Posture</h2>
          <div className={styles.alertBar}>
            <div className={`${styles.alert} ${data.tags.shadow === 0 ? styles.alertSuccess : styles.alertDanger}`}>
              <strong>Shadow APIs:</strong> {data.tags.shadow === 0 ? "None detected" : `${data.tags.shadow} found`}
            </div>
            <div className={`${styles.alert} ${styles.alertSuccess}`}>
              <strong>Prover endpoints:</strong> {data.tags.prover} &mdash; proof generation surface
            </div>
            <div className={`${styles.alert} ${styles.alertSuccess}`}>
              <strong>Verifier endpoints:</strong> {data.tags.verifier} &mdash; proof verification surface
            </div>
            <div className={`${styles.alert} ${styles.alertWarning}`}>
              <strong>Infrastructure:</strong> {data.services.filter((s) => s.port).length} services expose container ports
            </div>
          </div>
        </div>
      )}

      {/* Tab: Raw Data */}
      {activeTab === "raw" && (
        <div className={styles.rawSection}>
          <div className={styles.rawTabs}>
            {["json", "yaml", "openapi", "sarif"].map((fmt) => (
              <button key={fmt} className={`${styles.rawTab} ${rawTab === fmt ? styles.rawTabActive : ""}`} onClick={() => setRawTab(fmt)}>
                {fmt.toUpperCase()}
              </button>
            ))}
          </div>
          <div className={styles.rawBody}>
            <button className={styles.copyBtn} onClick={copyRaw}>{copied ? "Copied!" : "Copy"}</button>
            <pre className={styles.rawPre}>{getRawContent(rawTab)}</pre>
          </div>
        </div>
      )}

      {/* Download bar */}
      <div className={styles.downloadBar}>
        <button className={styles.downloadBtn} onClick={() => download("json")}>JSON</button>
        <button className={styles.downloadBtn} onClick={() => download("yaml")}>YAML</button>
        <button className={styles.downloadBtn} onClick={() => download("openapi")}>OpenAPI</button>
        <button className={styles.downloadBtn} onClick={() => download("sarif")}>SARIF</button>
        <button className={styles.downloadBtn} onClick={() => download("mermaid")}>Mermaid</button>
      </div>
    </div>
  );
}
