import React, { useState, useEffect, useMemo } from "react";
import styles from "./styles.module.css";

const SERVICE_ICONS = {
  server: "\uD83D\uDEE1\uFE0F",
  gateway: "\uD83D\uDEAA",
  "build-service": "\uD83D\uDD27",
  "prover-service": "\u2699\uFE0F",
  cli: "\uD83D\uDCBB",
};

const METHOD_CLASSES = {
  GET: styles.methodGet,
  POST: styles.methodPost,
  ANY: styles.methodAny,
  CLI: styles.methodCli,
  TCP: styles.methodTcp,
  CONFIG: styles.methodConfig,
};

const TAG_CLASSES = {
  health: styles.tagHealth,
  prover: styles.tagProver,
  verifier: styles.tagVerifier,
  shadow: styles.tagShadow,
  config: styles.tagConfig,
  docker: styles.tagDocker,
  cli: styles.tagCli,
  command: styles.tagCli,
};

export default function ScanDog() {
  const [data, setData] = useState(null);
  const [search, setSearch] = useState("");
  const [methodFilter, setMethodFilter] = useState("all");
  const [expandedServices, setExpandedServices] = useState(new Set());
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch("/scandog-data.json")
      .then((r) => r.json())
      .then((d) => {
        setData(d);
        setExpandedServices(new Set(d.services.map((s) => s.name)));
        setLoading(false);
      })
      .catch(() => setLoading(false));
  }, []);

  const toggleService = (name) => {
    setExpandedServices((prev) => {
      const next = new Set(prev);
      if (next.has(name)) next.delete(name);
      else next.add(name);
      return next;
    });
  };

  const filteredEndpoints = useMemo(() => {
    if (!data) return [];
    const eps = [];
    for (const svc of data.services) {
      for (const ep of svc.endpoints) {
        eps.push({ ...ep, _service: svc.name, _type: svc.type });
      }
    }

    return eps.filter((ep) => {
      if (methodFilter !== "all" && ep.method !== methodFilter) return false;
      if (search) {
        const q = search.toLowerCase();
        return (
          ep.path.toLowerCase().includes(q) ||
          ep.method.toLowerCase().includes(q) ||
          ep._service.toLowerCase().includes(q) ||
          ep.tags.some((t) => t.toLowerCase().includes(q))
        );
      }
      return true;
    });
  }, [data, search, methodFilter]);

  const download = (format) => {
    if (!data) return;
    let content = "";
    let ext = format;
    const mimeTypes = {
      json: "application/json",
      yaml: "text/yaml",
      openapi: "application/json",
      sarif: "application/json",
      html: "text/html",
      mermaid: "text/plain",
    };

    if (format === "json") {
      content = JSON.stringify(data, null, 2);
    } else {
      content = [
        "---",
        `# Zero Proof Attack Surface — ${format.toUpperCase()} Export`,
        `# Generated by ScanDog`,
        "---",
        JSON.stringify(data, null, 2),
      ].join("\n");
    }

    const blob = new Blob([content], { type: mimeTypes[format] || "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `zero-proof-attack-surface.${ext}`;
    a.click();
    URL.revokeObjectURL(url);
  };

  if (loading) {
    return (
      <div className={styles.container}>
        <div className={styles.hero}>
          <div className={styles.heroIcon}>ScanDog is sniffing around your codebase...</div>
        </div>
      </div>
    );
  }

  if (!data) {
    return (
      <div className={styles.container}>
        <div className={styles.hero}>
          <div className={styles.heroIcon}>Could not load scan data. Run the scanner first.</div>
        </div>
      </div>
    );
  }

  const serviceTypeIcons = {
    health: "\u2764\uFE0F",
    shadow: "\uD83D\uDC7B",
    prover: "\u2705",
    verifier: "\uD83D\uDD0D",
    config: "\u2699\uFE0F",
    docker: "\uD83D\uDC33",
  };

  return (
    <div className={styles.container}>
      <div className={styles.hero}>
        <div className={styles.heroIcon}>ScanDog</div>
        <h1 className={styles.heroTitle}>{data.projectName}</h1>
        <p className={styles.heroSub}>
          Attack Surface Report \u2022 {data.totalEndpoints} endpoints discovered across{" "}
          {data.services.length} services \u2022 {data.scannedAt}
        </p>
      </div>

      <div className={styles.statsGrid}>
        <div className={styles.statCard}>
          <div className={styles.statValue}>{data.totalEndpoints}</div>
          <div className={styles.statLabel}>Total Endpoints</div>
        </div>
        <div className={styles.statCard}>
          <div className={styles.statValue}>{data.services.length}</div>
          <div className={styles.statLabel}>Services</div>
        </div>
        <div className={styles.statCard}>
          <div className={styles.statValue}>{data.clis.length}</div>
          <div className={styles.statLabel}>CLI Tools</div>
        </div>
        <div className={styles.statCard}>
          <div className={`${styles.statValue} ${data.tags.shadow > 0 ? styles.statDanger : ""}`}>
            {data.tags.shadow}
          </div>
          <div className={styles.statLabel}>Shadow APIs</div>
        </div>
        <div className={styles.statCard}>
          <div className={styles.statValue}>{data.tags.prover}</div>
          <div className={styles.statLabel}>Prover Endpoints</div>
        </div>
        <div className={styles.statCard}>
          <div className={styles.statValue}>{data.tags.verifier}</div>
          <div className={styles.statLabel}>Verifier Endpoints</div>
        </div>
      </div>

      <div className={styles.filterBar}>
        <input
          className={styles.searchInput}
          type="text"
          placeholder="Search endpoints, services, or tags..."
          value={search}
          onChange={(e) => setSearch(e.target.value)}
        />
        <select
          className={styles.filterSelect}
          value={methodFilter}
          onChange={(e) => setMethodFilter(e.target.value)}
        >
          <option value="all">All Methods</option>
          <option value="GET">GET</option>
          <option value="POST">POST</option>
          <option value="ANY">ANY</option>
          <option value="CLI">CLI</option>
          <option value="TCP">TCP</option>
          <option value="CONFIG">CONFIG</option>
        </select>
        <span style={{ fontSize: "0.8rem", color: "var(--ifm-color-emphasis-500)" }}>
          {filteredEndpoints.length} of {data.totalEndpoints} endpoints
        </span>
      </div>

      {data.services.map((svc) => {
        const isExpanded = expandedServices.has(svc.name);
        const icon = SERVICE_ICONS[svc.type] || "\uD83D\uDCA1";
        const hasFiltered = svc.endpoints.some((ep) => {
          if (methodFilter !== "all" && ep.method !== methodFilter) return false;
          if (search) {
            const q = search.toLowerCase();
            return (
              ep.path.toLowerCase().includes(q) ||
              ep.method.toLowerCase().includes(q) ||
              ep.tags.some((t) => t.toLowerCase().includes(q))
            );
          }
          return true;
        });
        if (!hasFiltered && (search || methodFilter !== "all")) return null;

        return (
          <div className={styles.serviceCard} key={svc.name}>
            <div className={styles.serviceHeader} onClick={() => toggleService(svc.name)}>
              <span className={styles.serviceIcon}>{icon}</span>
              <span className={styles.serviceName}>{svc.name}</span>
              <span className={styles.serviceBadge}>{svc.type}</span>
              {svc.port ? <span className={styles.servicePort}>:{svc.port}</span> : null}
              <span className={`${styles.chevron} ${isExpanded ? styles.chevronOpen : ""}`}>&#9654;</span>
            </div>
            {isExpanded && (
              <table className={styles.endpointTable}>
                <thead>
                  <tr>
                    <th>Method</th>
                    <th>Path</th>
                    <th>Tags</th>
                    <th>Source</th>
                  </tr>
                </thead>
                <tbody>
                  {svc.endpoints
                    .filter((ep) => {
                      if (methodFilter !== "all" && ep.method !== methodFilter) return false;
                      if (search) {
                        const q = search.toLowerCase();
                        return (
                          ep.path.toLowerCase().includes(q) ||
                          ep.method.toLowerCase().includes(q) ||
                          ep.tags.some((t) => t.toLowerCase().includes(q))
                        );
                      }
                      return true;
                    })
                    .map((ep, i) => (
                      <tr key={i}>
                        <td>
                          <span className={`${styles.methodBadge} ${METHOD_CLASSES[ep.method] || styles.methodAny}`}>
                            {ep.method}
                          </span>
                        </td>
                        <td>
                          <code>{ep.path}</code>
                        </td>
                        <td>
                          <div className={styles.tagList}>
                            {ep.tags.map((t, j) => (
                              <span key={j} className={`${styles.tag} ${TAG_CLASSES[t] || ""}`}>
                                {t}
                              </span>
                            ))}
                          </div>
                        </td>
                        <td>
                          <a className={styles.sourceLink} href={`https://github.com/SURUJ404/Zero-proof/blob/main/${ep.source.file}`} target="_blank" rel="noopener">
                            {ep.source.file}:{ep.source.line}
                          </a>
                        </td>
                      </tr>
                    ))}
                  {svc.endpoints.filter((ep) => {
                    if (methodFilter !== "all" && ep.method !== methodFilter) return false;
                    if (search) {
                      const q = search.toLowerCase();
                      return (
                        ep.path.toLowerCase().includes(q) ||
                        ep.method.toLowerCase().includes(q) ||
                        ep.tags.some((t) => t.toLowerCase().includes(q))
                      );
                    }
                    return true;
                  }).length === 0 && (
                    <tr className={styles.emptyRow}>
                      <td colSpan={4}>No matching endpoints</td>
                    </tr>
                  )}
                </tbody>
              </table>
            )}
          </div>
        );
      })}

      {data.clis.length > 0 && (
        <div className={styles.serviceCard}>
          <div className={styles.serviceHeader} onClick={() => toggleService("cli-tools")}>
            <span className={styles.serviceIcon}>&#x1F4BB;</span>
            <span className={styles.serviceName}>CLI Tools</span>
            <span className={styles.serviceBadge}>&#x1F4CB; {data.clis.length}</span>
          </div>
          {expandedServices.has("cli-tools") && (
            <div style={{ padding: "1rem 1.25rem" }}>
              {data.clis.map((cli, i) => (
                <div key={i} style={{ marginBottom: "0.75rem" }}>
                  <strong style={{ color: "var(--ifm-color-primary)" }}>{cli.binary}</strong>
                  <p style={{ margin: "0.2rem 0 0.4rem", fontSize: "0.85rem", color: "var(--ifm-color-emphasis-600)" }}>
                    {cli.description}
                  </p>
                  <div style={{ display: "flex", gap: "0.4rem", flexWrap: "wrap" }}>
                    {cli.commands.map((cmd, j) => (
                      <code key={j} style={{ fontSize: "0.75rem", padding: "0.15rem 0.4rem" }}>
                        {cli.binary} {cmd.name}
                      </code>
                    ))}
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      )}

      <div className={styles.downloadBar}>
        <button className={styles.downloadBtn} onClick={() => download("json")}>
          Download JSON
        </button>
        <button className={styles.downloadBtn} onClick={() => download("yaml")}>
          Download YAML
        </button>
        <button className={styles.downloadBtn} onClick={() => download("openapi")}>
          Download OpenAPI
        </button>
        <button className={styles.downloadBtn} onClick={() => download("sarif")}>
          Download SARIF
        </button>
        <button className={styles.downloadBtn} onClick={() => download("mermaid")}>
          Download Mermaid
        </button>
      </div>
    </div>
  );
}
