name: Benchmark Check

on:
  push:
    branches: [main, "release-*"]
  pull_request:
    branches: [main, "release-*"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

env:
  RISC0_RUST_TOOLCHAIN_VERSION: 1.94.1
  RISC0_CPP_TOOLCHAIN_VERSION: 2024.01.05
  RISC0_SKIP_BUILD: 1
  RISC0_SKIP_BUILD_KERNELS: 1

jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - run: git lfs pull
      - uses: ./.github/actions/rustup
      - uses: ./.github/actions/sccache
      - uses: ./.github/actions/protoc
      - name: Install RISC Zero Rust toolchain
        run: cargo run --bin rzup -- --verbose install rust $RISC0_RUST_TOOLCHAIN_VERSION
      - name: Install RISC Zero C++ toolchain
        run: cargo run --bin rzup -- --verbose install cpp $RISC0_CPP_TOOLCHAIN_VERSION
      - name: Full build
        run: cargo build --release -F prove --locked --quiet
      - run: sccache --show-stats
